### ISSUE TITLE
JAVA 11 — Paper and ServerJars Updater

### ISSUE THREAD

**Issue by WINGS07** [jacobtread/ServerJars-Updater#4]
on startup I get this error:
`Unable to retrieve Instrumentation API to add Paper jar to ClassPath_`

My server runs JAVA 11, [ServerJars updater](serverjars.com/updater)

After successful installation, paper starts applying patches, and after that it just crashes with this error

JVM Flags:
```
java -Xms128M -Xmx3072M -Dterminal.jline=false -Dterminal.ansi=true -Djava.system.class.loader=com.serverjars.updater.ServerJarsLoader -jar upd.jar
```

![IMG_20201215_122729_698.jpg](https://user-images.githubusercontent.com/72886646/102196411-ed487300-3ed0-11eb-8193-12e21c9050f9.jpg)

**Comment by WINGS07** [comment]
Oh, I'm sorry, this is almost a duplicate of #4
But I use Java 11

**Comment by WINGS07** [comment]
[Here Paper's comment](https://github.com/PaperMC/Paperclip/issues/29#issuecomment-745167768)

**Comment by JONTTM** [comment]
Interesting I am getting a completely different issue with Java 11
https://github.com/jacobtread/ServerJars-Updater/issues/5

**Comment by WINGS07** [comment]
> Interesting I am getting a completely different issue with Java 11
> #5

I'm using 3GB & 2 CPU Cores
Host: hosting.superhub.xyz
This hosting using docker containers

**Comment by JONTTM** [comment]
Looks like the repo was moved to https://github.com/ServerJars/updater
You should try that to see if it fixes your issue. The owner of this repo has made a statement in readme.md that "all issues will be ignored"

**Comment by WINGS07** [comment]
Oh thanks! This updater supports Yatopia. This is exactly what I was looking for!
